export const FETCH_REACTIONSDATA_LOADING = 'FETCH_REACTIONSDATA_LOADING'
export const FETCH_REACTIONSDATA_SUCCESS = 'FETCH_REACTIONSDATA_SUCCESS'
export const FETCH_REACTIONSDATA_FAILED = 'FETCH_REACTIONSDATA_FAILED'
export const FETCH_REACTIONSDATA_ERROR = 'FETCH_REACTIONSDATA_ERROR'