// Constants
export const SETUP_REACTIONS = 'SETUP_REACTIONS'

// to content reactions
export const GET_CONTENT_REACTIONS_LOADING = 'GET_CONTENT_REACTIONS_LOADING'
export const GET_CONTENT_REACTIONS_SUCCESS = 'GET_CONTENT_REACTIONS_SUCCESS'
export const GET_CONTENT_REACTIONS_FAILED = 'GET_CONTENT_REACTIONS_FAILED'
export const GET_CONTENT_REACTIONS_ERROR = 'GET_CONTENT_REACTIONS_ERROR'

// to add reaction
export const PRESET_ADD_REACTION = 'PRESET_ADD_REACTION'
export const ADD_REACTION_LOADING = 'ADD_REACTION_LOADING'
export const ADD_REACTION_SUCCESS = 'ADD_REACTION_SUCCESS'
export const ADD_REACTION_FAILED = 'ADD_REACTION_FAILED'
export const ADD_REACTION_ERROR = 'ADD_REACTION_ERROR'


// to remove reaction
export const PRESET_REMOVE_REACTION = 'PRESET_REMOVE_REACTION'
export const REMOVE_REACTION_LOADING = 'REMOVE_REACTION_LOADING'
export const REMOVE_REACTION_SUCCESS = 'REMOVE_REACTION_SUCCESS'
export const REMOVE_REACTION_FAILED = 'REMOVE_REACTION_FAILED'
export const REMOVE_REACTION_ERROR = 'REMOVE_REACTION_ERROR'

export const FAILURE_UPLOAD_FILE = 'FAILURE_UPLOAD_FILE'